#pragma once

// Name: Polygon, Version: 0.3.13.76


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.Pistol
struct UBP_PG_AnimBluerpint_Body_C_Pistol_Params
{
	struct FPoseLink                                   Pistol;                                                    // (Parm, OutParm, NoDestructor)
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.Rifle
struct UBP_PG_AnimBluerpint_Body_C_Rifle_Params
{
	struct FPoseLink                                   Rifle;                                                     // (Parm, OutParm, NoDestructor)
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.AnimGraph
struct UBP_PG_AnimBluerpint_Body_C_AnimGraph_Params
{
	struct FPoseLink                                   AnimGraph;                                                 // (Parm, OutParm, NoDestructor)
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.FootStep
struct UBP_PG_AnimBluerpint_Body_C_FootStep_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.CalculateWeaponAimPosition
struct UBP_PG_AnimBluerpint_Body_C_CalculateWeaponAimPosition_Params
{
	struct FVector                                     ReturnValue;                                               // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_74F028D547839C82B37D349806DFD1C4
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_74F028D547839C82B37D349806DFD1C4_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_B2D8CB1A4EE971AA11B87A9BECBA1489
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_B2D8CB1A4EE971AA11B87A9BECBA1489_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_BlendListByEnum_624EC1604A8C7535E5E936B5892E280B
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_BlendListByEnum_624EC1604A8C7535E5E936B5892E280B_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_3E47825B4C24FD0F63091A8DF89701F5
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_3E47825B4C24FD0F63091A8DF89701F5_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_02FCAFD34F0ECABEBEB767B0DF4F81B7
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_02FCAFD34F0ECABEBEB767B0DF4F81B7_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_0ECAD4134B93A24988AAB7A04A3C6A09
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_0ECAD4134B93A24988AAB7A04A3C6A09_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_C21B4C764C42B932FAAAFFA0AEA81A24
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_C21B4C764C42B932FAAAFFA0AEA81A24_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_8F7FD22148DC73DC98AE7B808E7C4B33
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_8F7FD22148DC73DC98AE7B808E7C4B33_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_E3C4A658417E40D1141B48B1132CC4A6
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_E3C4A658417E40D1141B48B1132CC4A6_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_254314F74131FC5A859548853EB6497C
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_254314F74131FC5A859548853EB6497C_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_3C5BD8B04ABF3EF601AB69A26FACC147
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_ModifyBone_3C5BD8B04ABF3EF601AB69A26FACC147_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_20BE4E6F46BFA4812B726D9D87267119
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_20BE4E6F46BFA4812B726D9D87267119_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_699A03344FD27051BA99B6B743BAB17C
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_699A03344FD27051BA99B6B743BAB17C_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_1B47888E40E04734281DC1BF74290F9E
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_1B47888E40E04734281DC1BF74290F9E_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_73515F914209BDEBA61DEB87A6581BD6
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_73515F914209BDEBA61DEB87A6581BD6_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_7091672545B6B5EDBB1AF9B76DEAC5F1
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_7091672545B6B5EDBB1AF9B76DEAC5F1_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_0C6D11F9478C2CCA8D2B89AE302BC48F
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_0C6D11F9478C2CCA8D2B89AE302BC48F_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_1738CE6A4556CAC06CEDF2AC995649C2
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_1738CE6A4556CAC06CEDF2AC995649C2_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_C6B34994416FB5C4153AEE9DDBB3656B
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_C6B34994416FB5C4153AEE9DDBB3656B_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_45C76CD04FD592D6D9663F8806F3997A
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_45C76CD04FD592D6D9663F8806F3997A_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_9D154E244433268F1FE9FA8B6C11E767
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_9D154E244433268F1FE9FA8B6C11E767_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_7D9A87CD4139DE545FB29AB254A628E9
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_7D9A87CD4139DE545FB29AB254A628E9_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_AD8743C5445D626593CC2B94B08E96E6
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_AD8743C5445D626593CC2B94B08E96E6_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_47C1FB124BA8D7290D0BC5887AB7B32A
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_47C1FB124BA8D7290D0BC5887AB7B32A_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_46C1ECDE434330FC1817D3B3EFB3B0DD
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_46C1ECDE434330FC1817D3B3EFB3B0DD_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_4A44D57149ED502BBD357090319DE06D
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_4A44D57149ED502BBD357090319DE06D_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_8A9C2D3340D831EFB357FCAD8E2A5455
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_8A9C2D3340D831EFB357FCAD8E2A5455_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_33D3CA0B4E160CD17BF28BB9C0BE23F6
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_33D3CA0B4E160CD17BF28BB9C0BE23F6_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_0D0D0BE144386DC36B1543AEC8D22E88
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_0D0D0BE144386DC36B1543AEC8D22E88_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_3E2D3EB94E5D7A6EC9CA5A85B8DA5317
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_TransitionResult_3E2D3EB94E5D7A6EC9CA5A85B8DA5317_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.AnimNotify_FootStep
struct UBP_PG_AnimBluerpint_Body_C_AnimNotify_FootStep_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.AnimNotify_ThrowGrenade
struct UBP_PG_AnimBluerpint_Body_C_AnimNotify_ThrowGrenade_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.AnimNotify_Pistol_Draw
struct UBP_PG_AnimBluerpint_Body_C_AnimNotify_Pistol_Draw_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.AnimNotify_Weapon_Draw
struct UBP_PG_AnimBluerpint_Body_C_AnimNotify_Weapon_Draw_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.BlueprintUpdateAnimation
struct UBP_PG_AnimBluerpint_Body_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.BlueprintInitializeAnimation
struct UBP_PG_AnimBluerpint_Body_C_BlueprintInitializeAnimation_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_E5034F484E375AFE827350BD6D947F0F
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_E5034F484E375AFE827350BD6D947F0F_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_0B8059724B94E469E45888A975611E4F
struct UBP_PG_AnimBluerpint_Body_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_AnimGraphNode_SequenceEvaluator_0B8059724B94E469E45888A975611E4F_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.OnSetCurrentWeapon_Event
struct UBP_PG_AnimBluerpint_Body_C_OnSetCurrentWeapon_Event_Params
{
};

// Function BP_PG_AnimBluerpint_Body.BP_PG_AnimBluerpint_Body_C.ExecuteUbergraph_BP_PG_AnimBluerpint_Body
struct UBP_PG_AnimBluerpint_Body_C_ExecuteUbergraph_BP_PG_AnimBluerpint_Body_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
